export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL';
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
export const POST_ACTIVITY = 'POST_ACTIVITY';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const ORDER_COUNTRIES = 'ORDER_COUNTRIES';
export const FILTER_COUNTRIES = 'FILTER_COUNTRIES';
